blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/demaconsulting/SpdxTool/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ”’ Security Advisory
    url: https://github.com/demaconsulting/SpdxTool/security/advisories/new
    about: Report security vulnerabilities privately
